#include "stdafx.h"

#include "WarlockSpellDefinition.h"
#include <map>

using namespace std;

map<int, map<WarlockSpellType, SpellId>> WarlockSpellDefinition::warlockSpellByLevel = {
	{
		1 ,
{
	{ WARLOCK_IMMOLATE, WARLOCK_IMMOLATE_1 },
{ WARLOCK_SHADOW_BOLT, WARLOCK_SHADOW_BOLT_1 },
{ WARLOCK_DEMON_SKIN, WARLOCK_DEMON_SKIN_RANK_1 },
}
	},
	{
		2 ,
{
	{ WARLOCK_IMMOLATE, WARLOCK_IMMOLATE_1 },
{ WARLOCK_SHADOW_BOLT, WARLOCK_SHADOW_BOLT_1 },
{ WARLOCK_DEMON_SKIN, WARLOCK_DEMON_SKIN_RANK_1 },
}

	},
	{
		3,
{
	{ WARLOCK_IMMOLATE, WARLOCK_IMMOLATE_1 },
{ WARLOCK_SHADOW_BOLT, WARLOCK_SHADOW_BOLT_1 },
{ WARLOCK_DEMON_SKIN, WARLOCK_DEMON_SKIN_RANK_1 },
}

	},
	{
		4,
{
	{ WARLOCK_IMMOLATE, WARLOCK_IMMOLATE_1 },
{ WARLOCK_SHADOW_BOLT, WARLOCK_SHADOW_BOLT_1 },
{ WARLOCK_DEMON_SKIN, WARLOCK_DEMON_SKIN_RANK_1 },
}

	},
	{
		5,
{
	{ WARLOCK_IMMOLATE, WARLOCK_IMMOLATE_1 },
{ WARLOCK_SHADOW_BOLT, WARLOCK_SHADOW_BOLT_1 },
{ WARLOCK_DEMON_SKIN, WARLOCK_DEMON_SKIN_RANK_1 },
}
	},
	{
		6,
{
	{ WARLOCK_IMMOLATE, WARLOCK_IMMOLATE_1 },
{ WARLOCK_SHADOW_BOLT, WARLOCK_SHADOW_BOLT_2 },
{ WARLOCK_DEMON_SKIN, WARLOCK_DEMON_SKIN_RANK_1 },
}

	},
	{
		7,
{
	{ WARLOCK_IMMOLATE, WARLOCK_IMMOLATE_1 },
{ WARLOCK_SHADOW_BOLT, WARLOCK_SHADOW_BOLT_2 },
{ WARLOCK_DEMON_SKIN, WARLOCK_DEMON_SKIN_RANK_1 },
}

	},
	{
		8,
{
	{ WARLOCK_IMMOLATE, WARLOCK_IMMOLATE_1 },
{ WARLOCK_SHADOW_BOLT, WARLOCK_SHADOW_BOLT_2 },
{ WARLOCK_DEMON_SKIN, WARLOCK_DEMON_SKIN_RANK_1 },
}

	},
	{
		9,
{
	{ WARLOCK_IMMOLATE, WARLOCK_IMMOLATE_1 },
{ WARLOCK_SHADOW_BOLT, WARLOCK_SHADOW_BOLT_2 },
{ WARLOCK_DEMON_SKIN, WARLOCK_DEMON_SKIN_RANK_1 },
}
	},
	{
		10,
{
	{ WARLOCK_IMMOLATE, WARLOCK_IMMOLATE_2 },
{ WARLOCK_SHADOW_BOLT, WARLOCK_SHADOW_BOLT_2 },
{ WARLOCK_DEMON_SKIN, WARLOCK_DEMON_SKIN_RANK_2 },
}
	},
};
