#pragma once

#include "SpellDefinition.h"
#include <map>

using namespace std;

enum WarlockSpellType {
	/*
	WARLOCK AFFLICTION
	*/
	WARLOCK_CORRUPTION,
	WARLOCK_CURSE_OF_WEAKNESS,
	WARLOCK_LIFE_TAP,
	WARLOCK_CURSE_OF_AGONY,
	WARLOCK_FEAR,
	WARLOCK_DRAIN_SOUL,
	WARLOCK_CURSE_OF_RECKLESSNESS,
	WARLOCK_DRAIN_LIFE,
	WARLOCK_DRAIN_MANA,
	WARLOCK_CURSE_OF_TONGUES,
	WARLOCK_CURSE_OF_ELEMENTS,
	WARLOCK_SIPHON_LIFE,
	WARLOCK_HOWL_OF_TERROR,
	WARLOCK_DEATH_COIL,
	WARLOCK_CURSE_OF_SHADOW,
	WARLOCK_DARK_PACT,
	WARLOCK_CURSE_OF_DOOM,

	/*
	WARLOCK DEMONOLOGY
	*/
	WARLOCK_DEMON_SKIN,
	WARLOCK_CREATE_HEALTHSTONE,
	WARLOCK_HEALTH_FUNNEL,
	WARLOCK_UNENDING_BREATH,
	WARLOCK_CREATE_SOULSTONE,
	WARLOCK_DEMON_ARMOR,
	WARLOCK_RITUAL_OF_SUMMONING,
	WARLOCK_EYE_OF_KILROGG,
	WARLOCK_SENSE_DEMONS,
	WARLOCK_DETECT_INVISIBILITY,
	WARLOCK_BANISH,
	WARLOCK_CREATE_FIRESTONE,
	WARLOCK_ENSLAVE_DEMON,
	WARLOCK_SHADOW_WARD,
	WARLOCK_CREATE_SPELLSTONE,

	/*
	WARLOCK DESTRUCTION
	*/
	WARLOCK_SHADOW_BOLT,
	WARLOCK_IMMOLATE,
	WARLOCK_SEARING_PAIN,
	WARLOCK_RAIN_OF_FIRE,
	WARLOCK_SHADOWBURN,
	WARLOCK_HELLFIRE,
	WARLOCK_CONFLGRATE,
	WARLOCK_SOULFIRE,
};

class WarlockSpellDefinition {
	public:
		static SpellId getWarlockSpellIdByLevelAndSpellType(int level, WarlockSpellType spellType) {
			return warlockSpellByLevel[level][spellType];
		}

		static map<int, map<WarlockSpellType, SpellId>> warlockSpellByLevel;
};